<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        DB::table('users')->insert([
            [
                'name' => 'Abdul Ansheer M S',
                'email' => 'ansheer@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Abhijith R',
                'email' => 'abhijith@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Abhira V',
                'email' => 'abhira@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Abiraj P. R',
                'email' => 'abiraj@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ajai Mathew Jose',
                'email' => 'ajaimathew@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ajay Krishna',
                'email' => 'ajay.krishna@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ajaygopal Jayaprakash',
                'email' => 'ajaygopal@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Akhil Dileep',
                'email' => 'akhildileep@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Alex K J',
                'email' => 'alex@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Alfin Jiji',
                'email' => 'alfin@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Amal K K',
                'email' => 'amal@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Amal Pradeep',
                'email' => 'amal.p@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Amal T S',
                'email' => 'amal.ts@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ameen Sidhique M Y',
                'email' => 'ameen.s@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Anandu K Das',
                'email' => 'anandu@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Anju Gopi',
                'email' => 'anju.gopi@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Anto Stanly',
                'email' => 'antostanly@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Archana A',
                'email' => 'archana.a@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Arjun R Pillai',
                'email' => 'arjun@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Aswanth S',
                'email' => 'aswanth@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Athira S Nair',
                'email' => 's.athira@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ayana Santhosh',
                'email' => 'ayana@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Benjamin Shyam',
                'email' => 'benjamin@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Binil Baby',
                'email' => 'binil@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Binish George',
                'email' => 'binish@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chippy Surendran',
                'email' => 'chippy@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ciril James',
                'email' => 'ciril@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Deepak T S',
                'email' => 'deepak@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Devajith P',
                'email' => 'devajith@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dimple Dominic',
                'email' => 'dimple@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Elson V C',
                'email' => 'elson@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Grace Maria',
                'email' => 'grace@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hafis Safwan',
                'email' => 'hafis@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hrithik P',
                'email' => 'hrithik@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jayanth S',
                'email' => 'jayanth@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jayaraj P R',
                'email' => 'jayaraj@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jayesh Jayan',
                'email' => 'jayesh@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jiby George',
                'email' => 'jiby@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jijo S Chirakadavil',
                'email' => 'jijo.s@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jijomon KA',
                'email' => 'jijo@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jim M',
                'email' => 'jim@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jins Sebastian',
                'email' => 'jins@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Jithin Syam N S',
                'email' => 'jithin@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kiran T',
                'email' => 'kiran@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mohammed Rifas',
                'email' => 'rifas@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mrithula Ancy Arthur',
                'email' => 'mrithula@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Muhammed Ajmal',
                'email' => 'ajmal@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Muhammed Niyas V',
                'email' => 'niyas@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nabeel V',
                'email' => 'nabeel@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Najma Muhammed',
                'email' => 'najma@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Naveen Ambookken',
                'email' => 'naveen@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nibin Kurian',
                'email' => 'nibin@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nidhin CK',
                'email' => 'nidhin@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nijesh Mannuel',
                'email' => 'nijesh.m@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nikesh P',
                'email' => 'nikesh@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nikila Prasad',
                'email' => 'nikila@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nishad Muhammad',
                'email' => 'nishad.m@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nishanth K V',
                'email' => 'nishanth@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Noel Jose',
                'email' => 'noel@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Parvathy Krishnan',
                'email' => 'parvathy@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 1,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Prasheeth C S',
                'email' => 'prasheeth@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Praveen P',
                'email' => 'praveen@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rahul R',
                'email' => 'rahul@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Raj Mohan',
                'email' => 'rajmohan@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ramsiya P B',
                'email' => 'ramsiya@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Renjith C R',
                'email' => 'renjith@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Renjith Narayanan',
                'email' => 'renjith.n@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rex Jacob',
                'email' => 'rex@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rinu Rose Varghese',
                'email' => 'rinu@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rithin Dinesh',
                'email' => 'rithin@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rohith S',
                'email' => 'rohith@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Roniya K J',
                'email' => 'roniya@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sandeep E M',
                'email' => 'sandeep@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sanjay J',
                'email' => 'sanjay.j@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sarika K V',
                'email' => 'sarika@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sebin Francis',
                'email' => 'sebin@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Shahanaz B',
                'email' => 'shahanaz@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Shamil Erkara',
                'email' => 'shamil@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Shanoj K.S',
                'email' => 'shanoj@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Shine Sunil',
                'email' => 'shine@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sidharth A',
                'email' => 'sidharth@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sojo C J',
                'email' => 'sojo@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sreekuttan P S',
                'email' => 'sreekuttan@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sreenath E S',
                'email' => 'sreenath@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sreenath TK',
                'email' => 'sreenath.tk@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Swathy Sreenivasan',
                'email' => 'swathy@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Thajul Mushthaq',
                'email' => 'thajul@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Vijoy Varghese',
                'email' => 'vijoy@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Vineeth C K',
                'email' => 'vineeth@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Visakh K',
                'email' => 'visakh@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Vishnu V Sali',
                'email' => 'vishnu@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Vysakh Radhakrishnan',
                'email' => 'vysakh@quintetsolutions.com',
                'password' => Hash::make('password'),
                'role_id' => 4,
                'preference' => 'all_snacks',
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);
    }
}
